version: "3.9"
services:
  flask_docker:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    environment:
      DB_HOST: mysql
      DB_NAME: flask
      DB_USER: flask
      DB_PASSWORD: password123
    volumes:
      - .:/app
    links:
      - mysql
      - es01
    depends_on:
      - mysql
      - es01
    networks:
      - elastic
      - mysqlnet

  mysql:
    container_name: flask_mysql
    image: mysql:8
    volumes:
      - mysql-data:/val/lib/mysql
#    ports:
#       - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password123
      MYSQL_DATABASE: flask
      MYSQL_USER: flask
      MYSQL_PASSWORD: password123
    networks:
      - mysqlnet

  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - elastic

  kib01:
    image: docker.elastic.co/kibana/kibana:7.8.0
    container_name: kib01
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://es01:9200
      ELASTICSEARCH_HOSTS: http://es01:9200
    links:
      - es01
    networks:
      - elastic

volumes:
  mysql-data:
    driver: local
  data01:
    driver: local

networks:
  elastic:
    driver: bridge
  mysqlnet:
    driver: bridge