version: "3.9"
services:
  flask_docker:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    environment:
      DB_HOST: mysql
      DB_NAME: flask
      DB_USER: flask
      DB_PASSWORD: password123
    volumes:
      - .:/app
    links:
      - mysql
    depends_on:
      - mysql

  mysql:
    container_name: flask_mysql
    image: mysql:8
    volumes:
      - mysql-data:/val/lib/mysql
    # ports:
    #   - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password123
      MYSQL_DATABASE: flask
      MYSQL_USER: flask
      MYSQL_PASSWORD: password123

volumes:
  mysql-data:
    driver: local